name: Build QMK firmware
run-name: Running build by ${{ github.actor }}
on:
  push:
    branches:
      - main
      - dev

env:
  firmware_file: qmk_firmware/.build/celeste_default.bin

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
          path: qmk_firmware

      - name: Checkout Celeste
        uses: actions/checkout@v3
        with:
          path: qmk_firmware/keyboards/

      - name: Build firmware
        run: |
          qmk setup -H qmk_firmware -y
          qmk compile -kb celeste -km default

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: celeste_default.bin
          path: ${{ env.firmware_file }}
