name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
          - keymap.json

    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: vial-kb/vial-qmk
          submodules: recursive
          path: users/vial-qmk

      - name: Checkout userspace
        uses: actions/checkout@v3
        with:
          path: users/vial-qmk/keyboards/

      - name: Build firmware
        run: |
          qmk setup -H users/vial-qmk -y
          qmk compile -kb celeste -km vial

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: ${{ matrix.file }}_${{ github.actor }}
          path: |
            *.hex
            *.bin
            *.uf2
