name: Build QMK firmware
run-name: Running build by ${{ github.actor }}
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK-Vial
        uses: actions/checkout@v3
        with:
          repository: vial-kb/vial-qmk
          submodules: recursive
          path: vial-qmk

      - name: Checkout Celeste
        uses: actions/checkout@v3
        with:
          path: vial-qmk/keyboards/

      - name: Build firmware
        run: |
          qmk setup -H vial-qmk -y
          qmk compile -kb celeste -km vial

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: celeste_vial.bin
          path: |
            *.hex
            *.bin
            *.uf2
